### ISSUE TITLE
Incorrect path GTSM datasets Deltares data catalog

### ISSUE THREAD

**Issue by dvertegaal** [Deltares/hydromt#1016]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

The current piece of code in the Deltares data catalog for `gtsm_codec_reanalysis_{freq}_v1`  from: https://[raw.githubusercontent.com/Deltares/hydromt/50863d777404a4a91b5f66bf285b3edaa56713b1/data/catalogs/deltares_data.yml](https://raw.githubusercontent.com/Deltares/hydromt/50863d777404a4a91b5f66bf285b3edaa56713b1/data/catalogs/deltares_data.yml)
```
gtsm_codec_reanalysis_{freq}_v1:
  crs: 4326
  data_type: GeoDataset
  driver: netcdf
  kwargs:
    chunks:
      stations: 10
      time: -1
  meta:
    category: ocean
    paper_doi: 10.3389/fmars.2020.00263
    paper_ref: Muis at al (2020)
    source_license: https://cds.climate.copernicus.eu/api/v2/terms/static/licence-to-use-copernicus-products.pdf
    source_url: https://doi.org/10.24381/cds.8c59054f
    source_version: v1
  path: p:/11205028-c3s_435/01_data/01_Timeseries/timeseries2/{variable}/reanalysis_{variable}_{freq}_{year}_{month:02d}_v1.nc
  placeholders:
    freq: [10min, hourly, dailymax]
  rename:
    station_x_coordinate: lon
    station_y_coordinate: lat
    stations: index
```

### Current behaviour

Right now the path misses the new location **archivedprojects** where the project folder containing the data is moved to: `p:/11205028-c3s_435/01_data/01_Timeseries/timeseries2/{variable}/reanalysis_{variable}_{freq}_{year}_{month:02d}_v1.nc`

### Desired behaviour

As the project folder where the data is stored is moved to **archivedprojects**, the new path for `gtsm_codec_reanalysis_{freq}_v1` in the Deltares data catalog should be:
`p:/archivedprojects/11205028-c3s_435/01_data/01_Timeseries/timeseries2/{variable}/reanalysis_{variable}_{freq}_{year}_{month:02d}_v1.nc`
