### ISSUE TITLE
Re-enable dark / light modes

### ISSUE THREAD

**Issue by Huite** [Deltares/hydromt#1046]
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Kind of issue

Docs are wrong

### Documentation problem

Just a general heads-up: sphinx-pydata has much improved dark mode rendering. I've just re-enabled it for pandamesh and xugrid: https://deltares.github.io/pandamesh/

The GitHub and Deltares are ugly in dark mode, but a little CSS will turn them white:

```css
/* enlarge deltares & github icon size; only works with local/url svg files; not with fa icons */
img.icon-link-image {
    height: 2.5em !important;
}

[data-theme="dark"] img.icon-link-image[src*="deltares-blue.svg"] {
    filter: brightness(0) saturate(100%) invert(100%);
}
[data-theme="dark"] img.icon-link-image[src*="Octicons-mark-github.svg"] {
    filter: brightness(0) saturate(100%) invert(100%);
}
```

This might not solve all the issues brought up in #136, but it might be worthwhile to experiment locally. Seems like the logo is an SVG now; the getting started image has been altered.

You might be able to remove this line: https://github.com/Deltares/hydromt/blob/a707d44497ef493174b76fafde90e45085d78a6c/docs/conf.py#L262

Then add a little CSS and enjoy your dark mode.
