### ISSUE TITLE
Make a separate test bench for minimal installed hydromt

### ISSUE THREAD

**Issue by deltamarnix** [Deltares/hydromt#1147]
### Kind of request

Adding new functionality

### Enhancement Description

We should run a separate set of tests via GitHub actions where only a minimal set of hydromt + test is installed and tested.

```toml
[tool.pixi.environments]
py39-test = { features = ["py39", "test"], solve-group="py39" }
```

We have seen that some dependencies can cause problems when not fully installed. For example in #1145 , where there seemed to be a discrepancy between installing with mamba and installing with pip.

And the tests need to be run in the test matrix with the different python versions.
