### ISSUE TITLE
use ERA5 DestinE Earthdatahub with HydroMT catalog

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#1192]
### Kind of request

None

### Enhancement Description

To access ERA5 data via the DestinE Earthdatahub requires to use a token as explained [here](https://earthdatahub.destine.eu/getting-started)
This works with xarray using the syntax below, but the HydroMT DataCatalog equivelant raises an `NoDataException: resolver 'convention' found no files` How can we accommodate this data in HydroMT? Ideally the token is stored in a separate .netrc file, but I don't get that to work with only xarray either.

**With Xarray**
```py
import xarray as xr
PAT = "xxx" # personal token
ds = xr.open_dataset(
    f"https://edh:{PAT}@data.earthdatahub.destine.eu/copernicus-dem/GLO-30-v0.zarr",
    chunks={},
    engine="zarr",
    decode_coords="all",
    mask_and_scale=False,
)
ds
```

**With HydroMT/xarray**

Python code:
```py
from hydromt import DataCatalog
cat = DataCatalog("destine_data_v1.yml")
ds = cat.get_rasterdataset("era5_hourly")
ds
```

Data catalog file "destine_data_v1.yml" 
_Note_: that <PAT> needs to be replaced with actual token)
```yml
era5_hourly:
  data_type: RasterDataset
  uri: https://edh:<PAT>@data.earthdatahub.destine.eu/era5/reanalysis-era5-single-levels-v0.zarr
  driver:
    name: raster_xarray
    options:
      storage_options:
        client_kwargs:
          trust_env: true
      chunks: {}
      engine: zarr
    filesystem:
      protocol: https
```

### Use case

Access to this data resource would reduce maintenance burden on local downloaded data

### Additional Context

Possibly relates to #722 and #892
