### ISSUE TITLE
Enable parameter specific meta data in .yml file

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#147]
Currently we support setting the units metadata field for parameters in the RasterDatasetAdapter. It would be good to generalize this and be able to set any variable specific metadata in both DatasetAdapters. This could be done via the meta entry of a source in the yml file.

```
source_name:
   meta:
      paper_doi: xxx
      paper_ref: xxx
      <variable_name>: 
         units: xxx
         etc: xxx
```
