### ISSUE TITLE
ENH:  Support setting/updating meta data from data catalog (e.g., units)

### ISSUE THREAD

**Issue by Tjalling-dejong** [Deltares/hydromt#327]
### Feature Type

- Adding new functionality to HydroMT

### Enhancement Description

Add functionality that updates/sets the the meta data of datasets in the datacatalog. An example would be the unit of the data.

### Feature Description

Add `attrs` object in **data catalog yml file**
```
era5_hourly:
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  meta:
    category: meteo
  path: meteo/era5/{variable}/era5_{variable}_{year}_hourly.nc
  rename:
    t2m: temp
    tp: precip
  unit_add:
    temp: -273.15
  unit_mult:
    precip: 1000
  attrs:  
    temp: # var name
      units: degree C
      long_name: temperature
    precip:
      units: mm
```

In the **code**
- in `DataAdapter.__init__` add a `attrs` attribute
- in `RasterDatasetAdapter`, `GeoDatasetAdapter` (check if also possible for `DataFrameAdapter` and `GeoDataFrameAdapter`) after setting the global `meta` data, set the `attrs` for each variable with `ds[var].attrs.update(**self.attrs[var])`
- in `RasterDatasetAdapter` remove `units` argument which is duplicate with this enhancement.
