### ISSUE TITLE
DOC: Missing attrs example in the docs

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#468]
### HydroMT version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://github.com/Deltares/hydromt)

### Kind of issue

Docs are unclear

### Location of the documentation

https://deltares.github.io/hydromt/latest/user_guide/data_prepare_cat.html

### Documentation problem

The new attrs option is not enough documented in the prepare data catalog page.
Especially misses in the template catalog an example of how to use (I guess the variable name is based on new_varibale_name for example?)

<img width="470" alt="image" src="https://github.com/Deltares/hydromt/assets/45457510/bd1e88df-655b-4de4-a5b3-e59234ef29ff">

### Suggested fix for documentation

Add example to the template: EDIT: tested and solution 2 is the right format

```
attrs:
  units:
    new_variable_name: mm
  long_name:
    new_variable_name: variable_long_name
```

Or is it (?):

```
attrs:
  new_variable_name:
    units: mm
    long_name: variable_long_name
```
