### ISSUE TITLE
Include data catalogs in other data catalogs

### ISSUE THREAD

**Issue by dalmijn** [Deltares/hydromt#477]
### Kind of request

Adding new functionality

### Enhancement Description

The ability to include data catalog's (yaml's) via e.g. an include statement in another data catalog (e.g. final.yml). 
The desired result then would be that the datasets from all the data catalog's are available in HydroMT.

Take e.g. a data catalog (data_catalog1.yml)
```yaml
my_data:
  - meta: meta
```

And then include it in another data catalog (e.g. final.yml)
```yaml
include:
  - data_catalog1.yml
  - data_catalog2.yml

era5_daily:
  - stuff: stuff
  - more stuff: more stuff
```

And then just read this catalog via DataCatalog('./path_to/final.yml').

This would mean though that `include` is no longer available as a variable for a dataset.
How to include this is of course is up for debate. But I think this would be nice to have.

### Use case

Where data catalog yaml's would become very large or where there would be a lot of seperate data catalog yaml's to be put in the data_libs list.
