### ISSUE TITLE
Functionality to document and detect what slices in time and space a dataset covers

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#496]
### Kind of request

Adding new functionality

### Enhancement Description

This is essentially a copy of the necessary feature from the STAC spec. There an extent is needed to show what areas of spaced and time a dataset covers. In addition to being necessary for STAC compatibility, it is also just a very nice feature to have. It should be possible to document these in the data catalog entry itself, but there should also be functionality for the data adapters to deduce this from the data itself and report it. If at all possible the STAC spec should be followed for easier compatibility when we start work on STAC support. 

### Use case

The best way to do this will have to be determined but a possible solution for the data catalog could be: 

```yaml 
entry_name:
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  extent:
    spatial: 
       bbox: [-10,-10,10,10] 
     temporal:
       range: ["2023-08-30","2023-09-10"]
  kwargs:
    chunks:
      latitude: 250
      longitude: 240
      time: 30
    combine: by_coords
    decode_times: true
    parallel: true
  path: path/to/file.nc
``` 
A few consdierations for the format above are: 
- the units of course must be in the correct crs 
- You could argue this belongs to the meta sub dict, but since it's required for STAC I'm not sure I want to make it optional here. Therefore I think it might have to be outside the `meta` key but this is debatable

```python
spatial_extent = data_catalog.get_geodataset("data_set_name").get_spatial_extent()
temporal_extent = data_catalog.get_geodataset("data_set_name").get_temporal_extent()
```

what the `spatial_extent` etc. objects look like can still to be determined and there is something to be said for supporting multiple formats as it could also be useful for other adapters, but we will have to see how much work this would be to implement.
