### ISSUE TITLE
Adding support loading data from http[s]

### ISSUE THREAD

**Issue by jensdebruijn** [Deltares/hydromt#499]
### Kind of request

Adding new functionality

### Enhancement Description

Hello! Loading data from https is not supported, but is for example in rioxarray. This would be great to support, similar to s3. For example, the following datacatalog.yml specifies the path as https. This https url leads directly to a 13GB tif file of wind speed. 

```
global_wind_atlas:
  crs: 4326
  data_type: RasterDataset
  driver: raster
  path: https://globalwindatlas.info/api/gis/global/wind-speed/10
  meta:
    category: climate
    source_license: CC BY 4.0
    source_url: https://globalwindatlas.info
```

Loading this data in rioxarray works using the path of the entry in the data catalog. It is loaded within seconds and I can use (for example) `rio.clip_bbox` to select and download only the data that I want.

```
rxr.open_rasterio(self.data_catalog['global_wind_atlas'].path)
> xarray.DataArray ...
```

However, when doing the same thing directly using the ```get_raterdataset``` method of the data catalog, the following error occurs in `resolve_paths`: 
```
self.data_catalog.get_rasterdataset('global_wind_atlas')
> No such file found: https://globalwindatlas.info/api/gis/global/wind-speed/10
```

### Use case

Loading data remotely from https
