### ISSUE TITLE
Incorrect asset_gtype in open_geodataset

### ISSUE THREAD

**Issue by xldeltares** [Deltares/hydromt#508]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

In the function `open_geodataset`, the `assert_gtype` is always updated by string "Point". [line421]
That resulted error when trying to read polygon geodataset. 

```
1D_laterals_polygons:
  data_type: GeoDataFrame
  driver: vector
  path: local_data/laterals_polygons.geojson
  crs: 32647
1D_laterals_polygons_timeseries:
  path: local_data/laterals_polygons.geojson
  data_type: GeoDataset
  driver: vector
  crs: 32647
  rename:
    1D_laterals_polygons_timeseries: lateral_discharge
  kwargs:
    fn_data: local_data/laterals_series.csv
    assert_gtype: Polygon
```

### Current behaviour

Assertion Error about wrong geometry type

### Desired behaviour

No Error
