### ISSUE TITLE
Create data extract with HydroMT command line 

### ISSUE THREAD

**Issue by alimeshgi** [Deltares/hydromt#528]
### Kind of request

Adding new functionality

### Enhancement Description

To create data extract with HydroMT command line. More description will be added during the refinement procedure.

**Comment by savente93** [comment]
To yet be defined: what data to extract, and how to specify this?

**Comment by savente93** [comment]
```sh
hydromt extract <out_folder> -r <region>  [--compression=zip]? [source|file] [catalog]
```
input is EITHER source string, with optional provider and version, XOR a yaml file. Nice to have is the padas error pattern of "raise", "coerce", "ignore". Also add verbose option. 
also see https://deltares.github.io/hydromt/stable/_examples/export_data.html#Export-an-extract-of-the-data
use sourcedict in  code
CLI should override 
```yaml
meta:
   version: <hmt_version>

args:
   catalog: [<path>] 
   region: asdf

sources:
  - source: era5
     variables: [precip]
     provider: asdf
     version: asdf
```
