### ISSUE TITLE
Reading `GeoPandas` with HydroMT using `UPath` results in a `NotImplementedError`

### ISSUE THREAD

**Issue by Jaapel** [Deltares/hydromt#575]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

# Short example:

```python
from hydromt.gis_utils import parse_geom_bbox_buffer
from hydromt.io import open_vector
from upath.implementations.cloud import S3Path

path = S3Path(
    "s3://hydromt-data/topography/merit_hydro/basin_index.fgb",
)
crs = 4326
bbox = [9.566, 0.3476, 9.766, 0.5476]
geom = parse_geom_bbox_buffer(geom=None, bbox=bbox, buffer=0)

if __name__ == "__main__":
    open_vector(path, bbox=bbox, geom=geom, crs=crs)
```

# Long example

```python
import json
import logging
from os.path import join

import numpy as np
from hydromt import log
from hydromt.cli import cli_utils
from hydromt.models import MODELS

model = "wflow"
opt = None
model_root = "./wflow_small"
region = json.loads('{"subbasin": [9.666, 0.4476], "uparea": 100}')
config = "wflow-build.ini"
data = ["data_catalogs/deltares-data-curated-aws.yaml"]
verbose = 2
dd = False
fo = True
cache = False
quiet = 0

logger = logging.getLogger(__name__)


def build(
    model,
    model_root,
    opt,
    config,
    region,
    data,
    dd,
    fo,
    cache,
    verbose,
    quiet,
):
    """Build models from scratch.

    Example usage:
    --------------

    To build a wflow model for a subbasin using a point coordinates snapped to cells
    with upstream area >= 50 km2
    hydromt build wflow /path/to/model_root -i /path/to/wflow_config.ini  -r "{'subbasin': [-7.24, 62.09], 'uparea': 50}" -d deltares_data -d /path/to/data_catalog.yml -v

    To build a sfincs model based on a bbox
    hydromt build sfincs /path/to/model_root  -i /path/to/sfincs_config.ini  -r "{'bbox': [4.6891,52.9750,4.9576,53.1994]}"  -d /path/to/data_catalog.yml -v

    """  # noqa: E501
    log_level = max(10, 30 - 10 * (verbose - quiet))
    logger = log.setuplog(
        "build", join(model_root, "hydromt.log"), log_level=log_level, append=False
    )
    logger.info(f"Building instance of {model} model at {model_root}.")
    logger.info("User settings:")
    opt = cli_utils.parse_config(config, opt_cli=opt)
    kwargs = opt.pop("global", {})
    # Set region to None if empty string json
    if len(region) == 0:
        region = None
    # parse data catalog options from global section in config and cli options
    data_libs = np.atleast_1d(kwargs.pop("data_libs", [])).tolist()  # from global
    data_libs += list(data)  # add data catalogs from cli
    if dd and "deltares_data" not in data_libs:  # deltares_data from cli
        data_libs = ["deltares_data"] + data_libs  # prepend!
    try:
        # initialize model and create folder structure
        mode = "w+" if fo else "w"
        mod = MODELS.load(model)(
            root=model_root,
            mode=mode,
            logger=logger,
            data_libs=data_libs,
            **kwargs,
        )
        mod.data_catalog.cache = cache
        # build model
        mod.build(region, opt=opt)
    except Exception as e:
        logger.exception(e)  # catch and log errors
        raise
    finally:
        for handler in logger.handlers[:]:
            handler.close()
            logger.removeHandler(handler)


if __name__ == "__main__":
    build(
        model,
        model_root,
        opt,
        config,
        region,
        data,
        dd,
        fo,
        cache,
        verbose,
        quiet,
    )
```

with data catalog:
```yaml
---
meta:
  version: 2023.3

merit_hydro:
  alias: merit_hydro_v1.0
merit_hydro_v1.0:
  crs: 4326
  data_type: RasterDataset
  driver: raster
  filesystem: s3
  kwargs:
    chunks:
      x: 6000
      y: 6000
  meta:
    category: topography
    paper_doi: 10.1029/2019WR024873
    paper_ref: Yamazaki et al. (2019)
    source_license: CC-BY-NC 4.0 or ODbL 1.0
    source_url: http://hydro.iis.u-tokyo.ac.jp/~yamadai/MERIT_Hydro
    source_version: 1.0
  path: s3://hydromt-data/topography/merit_hydro/*.vrt
  rename:
    bas: basins
    dir: flwdir
    elv: elevtn
    slp: lndslp
    sto: strord
    upa: uparea
    upg: upgrid
    wth: rivwth

merit_hydro_index:
  alias: merit_hydro_index_v1.0
merit_hydro_index_v1.0:
  crs: 4326
  data_type: GeoDataFrame
  driver: vector
  filesystem: s3
  meta:
    category: topography
    paper_doi: 10.5194/hess-25-5287-2021
    paper_ref: Eilander et al. (2021)
    source_license: CC-BY-NC 4.0
  path: s3://hydromt-data/topography/merit_hydro/basin_index.fgb

merit_hydro_ihu:
  alias: merit_hydro_ihu_30sec_v1.0
merit_hydro_ihu_30sec_v1.0:
  crs: 4326
  data_type: RasterDataset
  driver: raster
  filesystem: s3
  kwargs:
    chunks:
      x: 6000
      y: 6000
  meta:
    category: topography
    paper_doi: 10.5194/hess-2020-582
    paper_ref: Eilander et al. (2021)
    source_license: ODC-By 1.0
    source_url: https://zenodo.org/record/5166932#.YVbxJ5pByUk
    source_doi: 10.5281/zenodo.5166932
    source_version: 1.0
  path: s3://hydromt-data/topography/merit_hydro_ihu/30sec/*.tif
  rename:
    30sec_basids: basins
    30sec_flwdir: flwdir
    30sec_elevtn: elevtn
    30sec_strord: strord
    30sec_uparea: uparea
    30sec_rivlen: rivlen
    30sec_rivslp: rivslp

merit_hydro_ihu_index:
  crs: 4326
  data_type: GeoDataFrame
  driver: vector
  filesystem: s3
  meta:
    category: topography
    paper_doi: 10.5194/hess-25-5287-2021
    paper_ref: Eilander et al. (2021)
    source_license: CC-BY-NC 4.0
    source_url: https://zenodo.org/record/5166932#.YVbxJ5pByUk
  path: s3://hydromt-data/topography/merit_hydro_ihu/30sec/basins.gpkg

rivers_lin2019_v1:
  data_type: GeoDataFrame
  driver: vector
  filesystem: s3
  meta:
    category: hydrography
    paper_doi: 10.5281/zenodo.3552776
    paper_ref: Lin et al. (2019)
    source_license: CC-BY-NC 4.0
    source_url: https://zenodo.org/record/3552776#.YVbOrppByUk
    source_version: 1
  path: s3://hydromt-data/hydrography/rivers_lin2019/rivers_ge30m.fgb
  rename:
    width_m: rivwth
    Q2: qbankfull

hydro_reservoirs:
  crs: 4326
  data_type: GeoDataFrame
  driver: vector
  filesystem: s3
  meta:
    category: surface water
    notes: GRanD.v1.1_HydroLAKES.v10_JRC.2016
    source_author: Alessia Matano
    source_version: 1.0
  nodata: -99
  path: s3://hydromt-data/hydrography/reservoirs/reservoir-db.fgb
  rename:
    Depth_avg: Depth_avg
    Dis_avg: Dis_avg
    G_CAP_MAX: Capacity_max
    G_CAP_MIN: Capacity_min
    G_CAP_REP: Capacity_norm
    G_DAM_HGT_: Dam_height
    Grand_id: waterbody_id
    Hylak_id: Hylak_id
    Lake_area: Area_avg
    Pour_lat: yout
    Pour_long: xout
    Vol_total: Vol_avg
  unit_mult:
    Area_avg: 1000000.0
    Capacity_max: 1000000.0
    Capacity_min: 1000000.0
    Capacity_norm: 1000000.0
    Vol_avg: 1000000.0

hydro_lakes:
  crs: 4326
  data_type: GeoDataFrame
  driver: vector
  filesystem: s3
  meta:
    category: surface water
    notes: HydroLAKES.v10_extract
    source_author: Arjen Haag
    source_version: 1.0
  path: s3://hydromt-data/hydrography/lakes/lake-db.fgb
  rename:
    Depth_avg: Depth_avg
    Dis_avg: Dis_avg
    Hylak_id: waterbody_id
    Lake_area: Area_avg
    Pour_lat: yout
    Pour_long: xout
    Vol_total: Vol_avg
  unit_mult:
    Area_avg: 1000000.0

rgi:
  alias: rgi_v0.6
rgi_v0.6:
  crs: 4326
  data_type: GeoDataFrame
  driver: vector
  filesystem: s3
  meta:
    category: surface water
    notes: Randolph Glacier Inventory
    paper_doi: 10.3189/2014JoG13J176
    paper_ref: Pfeffer et al. (2014)
    source_license: CC BY 4.0
    source_url: https://cds.climate.copernicus.eu/cdsapp#!/dataset/insitu-glaciers-extent?tab=overview
    source_version: 6.0
  path: s3://hydromt-data/hydrography/rgi/rgi.fgb
  rename:
    C3S_ID: C3S_id
    GLIMSID: GLIMS_id
    ID: simple_id
    RGIID: RGI_id

vito:
  alias: vito_2015_v2.0.2
vito_2015_v2.0.2:
  crs: 4326
  data_type: RasterDataset
  driver: raster
  filesystem: s3
  kwargs:
    chunks:
      x: 3600
      y: 3600
  meta:
    category: landuse
    paper_doi: 10.5281/zenodo.3939038
    paper_ref: Buchhorn et al (2020)
    source_url: https://land.copernicus.eu/global/products/lc
    source_version: v2.0.2
  path: s3://hydromt-data/landuse/vito/ProbaV_LC100_epoch2015_global_v2.0.2_discrete-classification_EPSG-4326.tif

modis_lai:
  alias: modis_mcd15a3h_v006
modis_mcd15a3h_v006:
  crs: 4326
  data_type: RasterDataset
  driver: raster
  filesystem: s3
  kwargs:
    chunks:
      x: 3600
      y: 3600
    concat: true
  meta:
    category: landuse
    notes: this dataset has been extracted from GEE ('MODIS/006/MCD15A3H') for the period '2003-01-01', '2017-12-31'
    paper_doi: 10.5067/MODIS/MCD15A3H.006
    paper_ref: Myneni et al (2015)
    source_license: https://lpdaac.usgs.gov/data/data-citation-and-policies/
    source_url: https://lpdaac.usgs.gov/products/mcd15a3hv006/
    source_version: MCD15A3H V006
  path: s3://hydromt-data/landuse/modis/MODIS_MCD15A3H_LAI/*.tif
  unit_mult:
    LAI: 0.1

soilgrids:
  alias: soilgrids_v1.0
soilgrids_v1.0:
  crs: 4326
  data_type: RasterDataset
  driver: raster
  filesystem: s3
  kwargs:
    chunks:
      x: 2400
      y: 2400
  meta:
    category: soil
    notes: "soilthickness is based on 1) soilgrids (global) and 2) dataset for Eurasia (ESDAC, 2004; Panagos et al., 2012): ESDAC, 2004. The european soil
      database distribution version 2.0, european commission and the European soil bureau\n network.  esdac.jrc.ec.europa.eu, accessed: 2017-11-17.  Panagos,
      P., Van Liedekerke, M., Jones, A., Montanarella, L., 2012. European soil data centre: Response to european policy support  and public data requirements.
      Land Use Policy 29 (2), 329â€“338. \n"
    paper_doi: 10.1371/journal.pone.0169748
    paper_ref: Hengl et al. (2017)
    source_license: ODbL
    source_url: https://www.isric.org/explore/soilgrids/faq-soilgrids-2017
    source_version: 2017
  path: s3://hydromt-data/soil/soilgrids_v1.0/*_250m_ll.tif
  rename:
    BLDFIE_M_sl1_250m_ll: bd_sl1
    BLDFIE_M_sl2_250m_ll: bd_sl2
    BLDFIE_M_sl3_250m_ll: bd_sl3
    BLDFIE_M_sl4_250m_ll: bd_sl4
    BLDFIE_M_sl5_250m_ll: bd_sl5
    BLDFIE_M_sl6_250m_ll: bd_sl6
    BLDFIE_M_sl7_250m_ll: bd_sl7
    CLYPPT_M_sl1_250m_ll: clyppt_sl1
    CLYPPT_M_sl2_250m_ll: clyppt_sl2
    CLYPPT_M_sl3_250m_ll: clyppt_sl3
    CLYPPT_M_sl4_250m_ll: clyppt_sl4
    CLYPPT_M_sl5_250m_ll: clyppt_sl5
    CLYPPT_M_sl6_250m_ll: clyppt_sl6
    CLYPPT_M_sl7_250m_ll: clyppt_sl7
    ORCDRC_M_sl1_250m_ll: oc_sl1
    ORCDRC_M_sl2_250m_ll: oc_sl2
    ORCDRC_M_sl3_250m_ll: oc_sl3
    ORCDRC_M_sl4_250m_ll: oc_sl4
    ORCDRC_M_sl5_250m_ll: oc_sl5
    ORCDRC_M_sl6_250m_ll: oc_sl6
    ORCDRC_M_sl7_250m_ll: oc_sl7
    PHIHOX_M_sl1_250m_ll: ph_sl1
    PHIHOX_M_sl2_250m_ll: ph_sl2
    PHIHOX_M_sl3_250m_ll: ph_sl3
    PHIHOX_M_sl4_250m_ll: ph_sl4
    PHIHOX_M_sl5_250m_ll: ph_sl5
    PHIHOX_M_sl6_250m_ll: ph_sl6
    PHIHOX_M_sl7_250m_ll: ph_sl7
    SLTPPT_M_sl1_250m_ll: sltppt_sl1
    SLTPPT_M_sl2_250m_ll: sltppt_sl2
    SLTPPT_M_sl3_250m_ll: sltppt_sl3
    SLTPPT_M_sl4_250m_ll: sltppt_sl4
    SLTPPT_M_sl5_250m_ll: sltppt_sl5
    SLTPPT_M_sl6_250m_ll: sltppt_sl6
    SLTPPT_M_sl7_250m_ll: sltppt_sl7
    SNDPPT_M_sl1_250m_ll: sndppt_sl1
    SNDPPT_M_sl2_250m_ll: sndppt_sl2
    SNDPPT_M_sl3_250m_ll: sndppt_sl3
    SNDPPT_M_sl4_250m_ll: sndppt_sl4
    SNDPPT_M_sl5_250m_ll: sndppt_sl5
    SNDPPT_M_sl6_250m_ll: sndppt_sl6
    SNDPPT_M_sl7_250m_ll: sndppt_sl7
    SoilThickness_250m_ll: soilthickness
    TAXOUSDA_250m_ll: tax_usda
  unit_mult:
    bd_sl1: 0.001
    bd_sl2: 0.001
    bd_sl3: 0.001
    bd_sl4: 0.001
    bd_sl5: 0.001
    bd_sl6: 0.001
    bd_sl7: 0.001
    oc_sl1: 0.1
    oc_sl2: 0.1
    oc_sl3: 0.1
    oc_sl4: 0.1
    oc_sl5: 0.1
    oc_sl6: 0.1
    oc_sl7: 0.1
    ph_sl1: 0.1
    ph_sl2: 0.1
    ph_sl3: 0.1
    ph_sl4: 0.1
    ph_sl5: 0.1
    ph_sl6: 0.1
    ph_sl7: 0.1

grdc:
  crs: 4326
  data_type: GeoDataFrame
  driver: xlsx
  filesystem: s3
  kwargs:
    index_col: grdc_no
  meta:
    category: observed data
    notes: GRDC-Station Catalogue, last downloaded 2020-07-16
    source_license: https://www.bafg.de/GRDC/EN/02_srvcs/21_tmsrs/210_prtl/tou.html;jsessionid=A56D50D4A36D3D8707CBF00CBD71F106.live11291?nn=2862854
    source_url: https://portal.grdc.bafg.de/applications/public.html?publicuser=PublicUser#dataDownload/StationCatalogue
  path: s3://hydromt-data/hydro/grdc/GRDC_Stations.xlsx
  rename:
    area: uparea

era5:
  alias: era5_daily
era5_daily:
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  filesystem: s3
  kwargs:
    chunks:
      latitude: 250
      longitude: 240
      time: 30
    combine: by_coords
    decode_times: true
    parallel: true
  meta:
    category: meteo
    notes: Extracted from Copernicus Climate Data Store; resampled by Deltares to daily frequency
    paper_doi: 10.1002/qj.3803
    paper_ref: Hersbach et al. (2019)
    source_license: https://cds.climate.copernicus.eu/cdsapp/#!/terms/licence-to-use-copernicus-products
    source_url: https://doi.org/10.24381/cds.bd0915c6
    source_version: ERA5 daily data on pressure levels
  path: s3://hydromt-data/meteo/era5_daily/nc_merged/era5_{year}*_daily.nc
  rename:
    d2m: temp_dew
    msl: press_msl
    ssrd: kin
    t2m: temp
    tisr: kout
    tmax: temp_max
    tmin: temp_min
    tp: precip
    u10: wind10_u
    v10: wind10_v
  unit_add:
    temp: -273.15
    temp_dew: -273.15
    temp_max: -273.15
    temp_min: -273.15
  unit_mult:
    kin: 0.000277778
    kout: 0.000277778
    ssr: 0.000277778
    press_msl: 0.01

era5_orography:
  crs: 4326
  data_type: RasterDataset
  driver: netcdf
  filesystem: s3
  kwargs:
    chunks:
      latitude: 120
      longitude: 125
  meta:
    category: meteo
    notes: Extracted from Copernicus Climate Data Store
    paper_doi: 10.1002/qj.3803
    paper_ref: Hersbach et al. (2019)
    source_license: https://cds.climate.copernicus.eu/cdsapp/#!/terms/licence-to-use-copernicus-products
    source_url: https://apps.ecmwf.int/codes/grib/param-db?id=129
  path: s3://hydromt-data/meteo/era5/meta/era5_orography_2018.nc
  rename:
    z: elevtn
  unit_mult:
    elevtn: 0.10197162129779283
```

and `wflow_build.ini`:

```ini
[setup_config]                  # options parsed to wflow ini file <section>.<option>
starttime = 2010-01-01T00:00:00
endtime = 2010-03-31T00:00:00
timestepsecs = 86400
input.path_forcing = inmaps-era5-2010.nc

[setup_basemaps]
hydrography_fn  = merit_hydro   # source hydrography data {merit_hydro, merit_hydro_1k}
basin_index_fn  = merit_hydro_index # source of basin index corresponding to hydrography_fn
upscale_method  = ihu           # upscaling method for flow direction data, by default 'ihu'
res             = 0.00833           # build the model at a 30 arc sec (~1km) resolution

[setup_rivers]
hydrography_fn   = merit_hydro      # source hydrography data, should correspond to hydrography_fn in setup_basemaps
river_geom_fn    = rivers_lin2019_v1 # river source data with river width and bankfull discharge
river_upa        = 30               # minimum upstream area threshold for the river map [km2]
rivdph_method    = powlaw           # method to estimate depth {'powlaw', 'manning', 'gvf'}
min_rivdph       = 1                # minimum river depth [m]
min_rivwth       = 30               # minimum river width [m]
slope_len        = 2000             # length over which tp calculate river slope [m]
smooth_len       = 5000             # length over which to smooth river depth and river width [m]
# river_routing    = local-inertial   # {'kinematic-wave', 'local-inertial'}

# [setup_floodplains] # if 2D floodplains are required
# hydrography_fn   = merit_hydro      # source hydrography data, should correspond to hydrography_fn in setup_basemaps
# floodplain_type = 2d #  # If two-dimensional floodplains are required
# elevtn_map = wflow_dem  # {'wflow_dem', 'dem_subgrid'}

# [setup_floodplains] # if 1D floodplains are required
# hydrography_fn   = merit_hydro      # source hydrography data, should correspond to hydrography_fn in setup_basemaps
# floodplain_type = 1d    # If one-dimensional floodplains are required
# flood_depths     = [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 4.0, 5.0] # flood depths at which a volume is derived


[setup_reservoirs]
reservoirs_fn   = hydro_reservoirs  # source for reservoirs shape and attributes
timeseries_fn   = gww           # additionnal source for reservoir are timeseries to compute reservoirs, Either 'gww' using gwwapi or 'jrc' using hydroengine.
min_area        = 1.0           # minimum lake area to consider [km2]

[setup_lakes]
lakes_fn        = hydro_lakes   # source for lakes based on hydroLAKES: {hydro_lakes}
min_area        = 10.0          # minimum reservoir area to consider [km2]

[setup_glaciers]
glaciers_fn     = rgi           # source for glaciers based on Randolph Glacier Inventory {rgi}
min_area        = 1.0           # minimum glacier area to consider [km2]

[setup_lulcmaps]
lulc_fn         = vito          # source for lulc maps: {globcover, vito, corine}

[setup_laimaps]
lai_fn          = modis_lai     # source for LAI: {modis_lai}

[setup_soilmaps]
soil_fn         = soilgrids     # source for soilmaps: {soilgrids}
ptf_ksatver     = brakensiek    # pedotransfer function to calculate hydraulic conductivity: {brakensiek, cosby}

[setup_outlets]
river_only = True

[setup_gauges]
gauges_fn       = grdc          # if not None add gaugemap. Either a path or known gauges_fn: {grdc}
snap_to_river   = True          # if True snaps gauges from source to river
derive_subcatch = False         # if True derive subcatch map based on gauges.

[setup_precip_forcing]
precip_fn       = era5          # source for precipitation.
precip_clim_fn  = None          # source for high resolution climatology to correct precipitation.

[setup_temp_pet_forcing]
temp_pet_fn     = era5          # source for temperature and potential evapotranspiration.
press_correction= True          # if True temperature is corrected with elevation lapse rate.
temp_correction = True          # if True pressure is corrected with elevation lapse rate.
dem_forcing_fn  = era5_orography # source of elevation grid corresponding to temp_pet_fn. Used for lapse rate correction.
pet_method      = debruin       # method to compute PET: {debruin, makkink}
skip_pet        = False         # if True, only temperature is prepared.

[setup_constant_pars]
KsatHorFrac=100
Cfmax = 3.75653
cf_soil = 0.038
EoverR = 0.11
InfiltCapPath = 5
InfiltCapSoil = 600
MaxLeakage = 0
rootdistpar = -500
TT = 0
TTI = 2
TTM = 0
WHC = 0.1
G_Cfmax = 5.3
G_SIfrac = 0.002
G_TT = 1.3
```

### Current behaviour

`geopandas` always calls `S3Path.expand_user`: https://github.com/geopandas/geopandas/blob/main/geopandas/io/file.py#L273
`Upath` then has a `NotImplementedError`: https://github.com/fsspec/universal_pathlib/blob/main/upath/core.py#L577C9-L577C19

### Desired behaviour

The HydroMT `io` module should be able to read S3 locations into a GeoDataFrame.
