### ISSUE TITLE
Improve export CLI

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt#657]
### Kind of request

Changing existing functionality

### Enhancement Description

I had a quick look at what was done in PR #627. Nice start!
I have a few suggestions or things to discuss before we also officially add this function to our docs in #644

First a bug:

- region argument is not passed to the export_data function (and should be converted to bbox first)

Then comments:

- check typos in the docstrings 
- in the docstrings, I feel using '.' for the mandatory path argument instead of path/to/output_dir is less clear. Also compared to other command line examples for build/update
- CLI args option name: -f is used for config file while in build/update we use -i. Do you think we should harmonize and use -i here as well?
- CLI args option name: here might be completely my taste but would -s instead of -t for source names be possible? -s sounds maybe closer to data source compared to target?
- add CLI args option: would it be possible to add an option in CLI for time tuple? Then in really most cases, you don't need a config file, unless for advanced options.
- support all arguments of the export data functions from the config file (unit_add, meta, append)
- nice-to-have: support multiple sources option (current -t) from CLI like we support multiple data catalogs option (-d) in build/update
- format of the config file: might be taste again but I feel that separating args and sources does not feel so clear to me.. could maybe all arguments be put on the same level and naming following a little closer the arguments of the export_data function? Also not sure why dictionary is necessary for each new source? (also data_libs is used instead of catalog in build/update and I am not sure what is the tuple syntax in yaml). My idea would be something like:

```
export:
  region: 
    - subbasin: [-7.24, 62.09]
    - uparea: 50
  data_libs:
    - tests/data/test_sources.yml
  time_tuple: (2010-01-01, 2020-12-31)
  source_names:
    - hydro_lakes[precip]
    - gtsmv3_eu_era5
  unit_conversion: False
  append: False
  meta: 
    version: 0.1
```
