### ISSUE TITLE
gadm dataset to FlatGeobuf's; add all entries to catalog

### ISSUE THREAD

**Issue by dalmijn** [Deltares/hydromt#686]
### Kind of request

Changing existing functionality

### Enhancement Description

The `gadm` dataset is currently in a `gpkg` (GeoPackage), with entries listed for some layers  (not all, one is also listed incorrectly).
This is incredibly slow, while the FlatGeobuf driver provides some much needed speed for a dataset of this size.
I'd propuse to ship all layers of the `gpkg` to seperate `FlatGeobuf` files. So one file per layer. 

This could look like:
- gadm_level0.fgb
- gadm_level1.fgb
- etc...

I would have all these layers added to the datacatalog as well under the same name as the files:

```yaml
gadm_level0:
  crs: 4326
  data_type: GeoDataFrame
  driver: vector
  meta:
    < meta entries >
  path: < path to file > # relative to root path
  rename:
    < rename if needed >

gadm_level1:
  < same stuff >
```

### Use case

I cannot directly list all cases as I do not know who uses it for what.
But for the new water demand feature in `hydromt_wflow` the `gadm` dataset will play a big part.
