### ISSUE TITLE
Simplify data drivers

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#720]
### Kind of request

Currently, `DataAdapter`s are responsible for both the representation of different data sources in the `DataCatalog`, reading in the data and transforming the data to a uniform data representation in memory. This makes the class responsible for a lot of functions and hard to modify or extend by the plugins.

### Enhancement Description

We propose that a `Driver` should be responsible for reading the data and creating a memory representation, while the `Adapter` should do generic transformations and filtering/slicing. A `DataSource` should represent items in the `DataCatalog`, which can check at read time whether all the required fields are present.

### Use case

This should make testing and maintenance easier, while being more flexible to customize for plugins.

**Comment by Jaapel** [comment]
Posting https://github.com/Deltares/hydromt/issues/432 here for reference discussions

**Comment by Jaapel** [comment]
Look at this `DataCatalog` entry:
```yaml
gtsm_codec_reanalysis_{freq}_v1:
  crs: 4326
  data_type: GeoDataset
  driver: netcdf
  kwargs:
    chunks:
      stations: 10
      time: -1
  meta:
    category: ocean
    paper_doi: 10.3389/fmars.2020.00263
    paper_ref: Muis at al (2020)
    source_license: https://cds.climate.copernicus.eu/api/v2/terms/static/licence-to-use-copernicus-products.pdf
    source_url: https://doi.org/10.24381/cds.8c59054f
    source_version: v1
  path: p:/11205028-c3s_435/01_data/01_Timeseries/timeseries2/{variable}/reanalysis_{variable}_{freq}_{year}_{month:02d}_v1.nc
  placeholders:
    freq: [10min, hourly, dailymax]
  rename:
    station_x_coordinate: lon
    station_y_coordinate: lat
    stations: index
```
There is a placeholder in the title entry, which can easily be expanded using the `placeholders` entry in the yaml document. But what about the `path` entry? There the `freq` is coming back, but there are also `year`, `month` and `variable`. For `RasterDataset` there is also `zoom_level`.
Is this some generic behavior for certain datasets or can we just use this in the more generic `DataSource` classes (e.g. `RasterDataSource`? want to split out the `_resolve_paths` between what the driver should be responsible for (remote data access -> `filesystem.glob`) and what is generic over multiple different data sources (handling name conventions). @DirkEilander @hboisgon do you think these naming conventions are truly generic? So far the logic seems to be to fill in and capture these "known" placeholders and if you do not recognize the placeholder, place `*`.
Did I miss any behavior?

**Comment by hboisgon** [comment]
Let me try to answer:
``placeholder`` is really different from the others because it helps to define multiple data sources (from the same dataset) that have exactly the same reading attributes apart from the path. The best example where we use this is cmip6 data where we can define in one data catalog entry 23*2 data sources:

``` yaml
cmip6_{model}_historical_{member}_{timestep}:
  crs: 4326
  data_type: RasterDataset
  driver: zarr
  filesystem: gcs
  kwargs:
    drop_variables: [time_bnds, lat_bnds, lon_bnds, bnds]
    decode_times: true
    preprocess: harmonise_dims
    consolidated: true
  meta:
    category: climate
    paper_doi: 10.1175/BAMS-D-11-00094.1
    paper_ref: Taylor et al. 2012
    source_license: CC BY 4.0
    source_url: https://console.cloud.google.com/marketplace/details/noaa-public/cmip6?_ga=2.136097265.-1784288694.1541379221&pli=1
    source_version: 1.3.1
  placeholders:
    model: [IPSL/IPSL-CM6A-LR, SNU/SAM0-UNICON, NCAR/CESM2, NCAR/CESM2-WACCM, INM/INM-CM4-8, INM/INM-CM5-0, NOAA-GFDL/GFDL-ESM4, NCC/NorESM2-LM, NIMS-KMA/KACE-1-0-G,
      CAS/FGOALS-f3-L, CSIRO-ARCCSS/ACCESS-CM2, NCC/NorESM2-MM, CSIRO/ACCESS-ESM1-5, NCAR/CESM2-WACCM-FV2, NCAR/CESM2-FV2, CMCC/CMCC-CM2-SR5, AS-RCEC/TaiESM1,
      NCC/NorCPM1, IPSL/IPSL-CM5A2-INCA, CMCC/CMCC-CM2-HR4, CMCC/CMCC-ESM2, IPSL/IPSL-CM6A-LR-INCA, E3SM-Project/E3SM-1-0]
    member: [r1i1p1f1]
    timestep: [day, Amon]
  path: gs://cmip6/CMIP6/CMIP/{model}/historical/{member}/{timestep}/{variable}/*/*
  rename:
    pr: precip
    tas: temp
    rsds: kin
    psl: press_msl
  unit_add:
    temp: -273.15
  unit_mult:
    precip: 86400
    press_msl: 0.01
```
So ``placeholder`` is really something that would be true for all of the ``DataSource`` types and all placeholders keywords should findable in the path.

The rest are "known" keywords in the path that hydromt can use to directly slice data when reading a data source. For example in some get_data methods you can pass ``time_tuple`` (then uses ``year``, ``month`` keywords if present) or ``variables`` list (then uses the ``variable`` keyword if present). In the case of your example or ERA5, if you request in get_data to only get precipitation for a year, this allows hydromt to read only one file precip_2001.nc instead of all netcdf files for all years and all variables before slicing (so faster and potentially less memory consumption).

But then like ``zoom_level`` all these keywords may not be applicable to all types of ``DataSource``. Not sure by heart which applies to which but basically you can check the drivers arguments and see if you can pass to it ``time_tuple``, ``variables`` and/or ``zoom_level``.

Maybe one final example to try and understand the difference between ``placeholder`` and known keywords:

``` python
# Placeholders have to be replaced in the data source name to get the data and keywords can be passed in the get_data ethods arguments
data_catalog.get_geodataset("gtsm_codec_reanalysis_hourly_v1", variables = ["precip"], time_tuple=("2010-01-01", "2010-03-31"))
# Get the 10min version of the dataset instead for all times and variables
data_catalog.get_geodataset("gtsm_codec_reanalysis_10min_v1")
```
