### ISSUE TITLE
Should top level functions in model yaml config be a list instead of a dictionary

### ISSUE THREAD

**Issue by savente93** [Deltares/hydromt#816]
### Kind of request

Changing existing functionality

### Enhancement Description

Currently the model config yaml file has a dictionary at as the root object:
```yaml
setup_config:
  header.settings: value
  timers.end: '2010-02-15'
  timers.start: '2010-02-05'

setup_grid:
  res: 0.05
  crs: 4326
  basin_index_fn: merit_hydro_index
  hydrography_fn: merit_hydro

setup_grid_from_constant:
  constant: 0.01
  name: c1
  dtype: float32
  nodata: -99.0

setup_grid_from_rasterdataset:
  raster_fn: merit_hydro_1k
  variables:
    - elevtn
    - basins
  reproject_method:
    - average
    - mode

setup_grid_from_rasterdataset2:
  raster_fn: vito
  fill_method: nearest
  reproject_method: mode
  rename:
    vito: landuse

```
This requires the hack of adding a 2 at the end of the `setup_grid_from_rasterdataset` to allow for calling a function more than once. Additionally, hydromt currently relies on the ordering of the function calls for correct behavioiur. However, some tools will sort dictionaries by alphabetical order because in dictionaries (outside python) do not have stable ordering. This is reinforced by PyYaml having options like `sort_keys` in it's read method. For now this is working, but it's increasing the chacnes that orders are going to ge tmodified. If the top lvel would be a list instead, this would solve this potential issue. The new format then would be:
```yaml
---
- setup_config:
    header.settings: value
    timers.end: '2010-02-15'
    timers.start: '2010-02-05'

- setup_grid:
    res: 0.05
    crs: 4326
    basin_index_fn: merit_hydro_index
    hydrography_fn: merit_hydro

- setup_grid_from_constant:
    constant: 0.01
    name: c1
    dtype: float32
    nodata: -99.0

- setup_grid_from_rasterdataset:
    raster_fn: merit_hydro_1k
    variables:
      - elevtn
      - basins
    reproject_method:
      - average
      - mode

- setup_grid_from_rasterdataset:
    raster_fn: vito
    fill_method: nearest
    reproject_method: mode
    rename:
      vito: landuse
```

### Use case

For people who don't know yaml outside of hydromt this maybe doesn't make a big difference but for people who know yaml from other places this communicates intent much clearer.  It also reduces the chances that other files such as linters will accidentally reorder the file unintentionally. 

### Additional Context

Github actions also does this:
```yaml
    steps:

      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.5.1
        with:
          pixi-version: "latest"
          environments: full-py${{ matrix.python-version }}
      - name: Prepare pixi
        run: |
          pixi run --locked -e full-py${{ matrix.python-version }} install-hydromt
```

**Comment by savente93** [comment]
Wouldn't the new component need a name to identify the component anyway? so like 
```yaml

- setup_grid_from_rasterdataset:
    component_name: "main_grid"
    raster_fn: merit_hydro_1k
    variables:
      - elevtn
      - basins
    reproject_method:
      - average
      - mode
```
We could also opt for some special syntax like 
- setup_grid_from_rasterdataset$main_grid:
    raster_fn: merit_hydro_1k
    variables:
      - elevtn
      - basins
    reproject_method:
      - average
      - mode
```
Not a huge van of inventing special syntax but it's possible.

**Comment by hboisgon** [comment]
I don't think it will conflict. At the model level you'll have a list of components that will have different names eg grid: GridrModelComponent and subgrid:GridModelComponent.

So with the new refactor then it would be:

``` yaml
grid.add_data_from_rasterdataset:
  raster_fn: merit_hydro
  reproject_method: average

subgrid.add_data_from_rasterdataset:
  raster_fn: vito
  reproject_method: mode

```

This said I think I quite like the idea of using a list. The numbering is not very well known by users and I think a list makes it clearer how you can then use the same function several times. Also good to ensure that order is kept as this is crucial for hydromt and model building.
