### ISSUE TITLE
Refactor `meta` as `metadata` as part of the `DataSource` instead of `DataAdapter`

### ISSUE THREAD

**Issue by Jaapel** [Deltares/hydromt#901]
### Kind of request

Changing existing functionality

### Enhancement Description

We reuse this information in multiple places.
We want to clarify that CRS and nodata are only used to fill missing metadata, and have no effect on reading the data.

MetaData should still be supplied to:
`DataSource.driver.resolve_and_read`
`DataSource.data_adapter.transform`

`DataSource.driver.metadata_resolver.resolve` also needs the `DataAdapter`.

Example `DataCatalog` entry:
```yaml
mysource:
        crs: 4326
        data_type: RasterDataset
        uri: meteo/era5_daily/nc_merged/era5_{year}*_daily.nc
        driver:
            name: netcdf
            filesystem: local
            metadata_resolver: convention
            options:
                chunks:
                    latitude: 250
                    longitude: 240
                    time: 30
                combine: by_coords
            ...
        meta:
            crs: 4326 # or EGPS:4326
            nodata: -9999
            extent:
                spatial: [4.5, 51.5, 8.5, 53.5]
                temporal: [2010-01-01, 2010-12-31]
            category: meteo
            notes: Extracted from Copernicus Climate Data Store; resampled by Deltares to daily frequency
            ...
        data_adapter:
            rename:
                d2m: temp_dew
                msl: press_msl
                ...
            unit_add:
                temp: -273.15
                temp_dew: -273.15
                ...
            unit_mult:
                kin: 0.000277778
                kout: 0.000277778
                ...
```

### Use case

More intuitive `DataCatalog` structure
