### ISSUE TITLE
expose class rather than submodule with plugin entrypoints

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#958]
### Kind of request

Changing existing functionality

### Enhancement Description

In v0.x we used the entrypoints to expose a class. In v1.x entrypoints expose a submodule. 

This has two disadvantages that require (large) changes from user and plugin that are not necessary in my opinion: 
- this poses strict requirements on a plugin structure, i.e. the model class must be in a submodule and should be the only thing exposed in that submodule. This is currently not the case for any plugin and also poses limitations on the file structure of the core.
- the name of the class is used as the name of the entrypoint which is used in our CLI, i.e. before the WflowModel class was know as the "wflow" entrypoint and hence the build command was `hydromt build wflow ...`. Now the entrypoint name is unused and the name becomes "WflowModel", hence the command is `hydromt build WflowModel ...`. I would like to keep the former for consistency and simplicity.

I couldn't find any discussion on the new implementation or big advantages,. One advantage I see is that that it is shorter in the toml file.

Unless there are other major advantages, I suggest to expose the class itself again with entrypoints like we did in v0.x.

### Use case

hydromt CLI

**v0.x (entrypoint exposed a class; this is how I suggest it functions)**

```toml
[project.entry-points."hydromt.models"]
wflow = "hydromt_wflow.wflow.WflowModel" # class in wflow.py
```

```bash
hydromt build wflow ...
```

**v1.x (entrypoint exposes a submodule; new implementation)**

```toml
[project.entry-points."hydromt.models"]
wflow = "hydromt_wflow.wflow"  # this is a script and not a subclass in hydromt_wflow; hence it wouldn't work in the current approach if I understand correctly
```

```bash	
hydromt build WflowModel ..
```

### Additional Context

We can slightly modify the v0.x `get_plugin_eps` function to update the v1 `_discover_plugins` function, see https://github.com/Deltares/hydromt/blob/ad2548e43f30b84488e55a4afe3414a0d1f7a87d/hydromt/models/model_plugins.py#L47
