### ISSUE TITLE
discuss possible merge of placeholder and variant concepts in `DataCatalog`

### ISSUE THREAD

**Issue by DirkEilander** [Deltares/hydromt#965]
### Kind of request

Changing existing functionality

### Enhancement Description

- Placeholders allow to define multiple sources in a short data catalog item. Each item gets its own unique name but all parameters, except for the file paths, have to be the same.
- Variants allow for sources with different versions or providers. Other variants, e.g. different data resolution, model (e.g. CMIP), etc.  

### Use case

We should discuss if we want to merge these concept to have a simpler interface for users

**Comment by Jaapel** [comment]
Suggested yaml:
```yaml
my_nice_source:
  variant_keys:
    - metadata.provider
    - metadata.crs
    - driver.filesystem
  variants:
    - uri: s3://bucket/key1/key2.json
      metadata:
        crs: 4326
      driver:
        provider: organisation1
        filesystem: s3
    - uri: /mnt/p/cooldata.json
      metadata:
        crs: 90002
      driver:
        filesystem: local
        provider: organization2
```
Where `variant_keys` are keys that uniquely define the variant, which should be present in each variant definition. Other fields like `uri` can overwrite the source definition. dots in `variant_keys` define nested fields.
